kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-claim-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: nfs-pv-1
